export type SarcasmParameterType = {
  input: string;
  result: string;
};

type SarcasmFunction = ({ input, result }: SarcasmParameterType) => string;

const handleEasyAddition: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Oh nice, ${input} = ${result}. Bet you feel like a math prodigy now. 🙃📚`,
    `Wow, ${input} equals ${result}. Did your calculator beg for mercy or what? 😏🤖`,
    `So ${input} gives ${result}? Groundbreaking. NASA’s probably calling you. 🚀🛰️`,
    `Congrats, you just reinvented the wheel with ${input} = ${result}. Slow clap. 👏😒`,
    `Look at you, ${input} resulting in ${result}. Did you stay up all night for this? 🥱🕰️`,
    `Hold up, ${input} equals ${result}. Someone alert the math police. 🚨👮‍♂️`,
    `Math level: ${input} = ${result}. Expert? More like “please stop.” 🙄🔢`,
    `Oh wow, ${input} gave ${result}. Even my pet rock could do that. 🪨🤷‍♂️`,
    `You really typed ${input} just to get ${result}? Living on the edge, huh? 😎🔥`,
    `Big brain moment: ${input} = ${result}. Calculator’s still recovering. 🧠💥`,
    `You call that math? ${input} equals ${result}. Yawn. 😴📉`,
    `Sure, ${input} results in ${result}. But did you even try? 🤔🎯`,
    `Guess what? ${input} = ${result}. I’m impressed...ly not. 😐📉`,
    `Oh wow, ${input} equals ${result}. Hold my coffee while I pretend to care. ☕️🙃`,
    `You solved ${input} and got ${result}? Alert the media. 📢🗞️`,
    `Math wizardry or nah? ${input} gave ${result}. Hard pass. 🧙‍♂️❌`,
    `Congrats, ${input} = ${result}. Next up: breathing. 🫁✨`,
    `${input} resulting in ${result}? This math journey is wild. Said no one ever. 😬📊`,
    `Did you just do ${input} to get ${result}? Calculator’s feeling used. 🤖💔`,
    `Hold tight, ${input} = ${result}. That’s some next-level basic stuff. 🔥😅`,
    `You got ${result} from ${input}? That’s math for champs... or not. 🏆🤡`,
    `Impressive: ${input} equals ${result}. Said nobody ever. 🙃🚫`,
    `Oh yeah, ${input} gives ${result}. Math thriller of the year. 🎬🍿`,
    `You just blew my mind with ${input} = ${result}. Or maybe not. 🤯😑`,
    `Plot twist: ${input} results in ${result}. Riveting stuff. 🌀📉`,
    `Math genius alert: ${input} equals ${result}. And here I thought calculators did the work. 🤖📱`,
    `Whoa, ${input} gives ${result}. Calculator probably needed a break after that. 😤⚡️`,
    `You typed ${input} and got ${result}? Math has never been so… predictable. 📉💤`,
    `Big brain flex: ${input} = ${result}. Now back to normal life. 🧠➡️😴`,
    `So ${input} equals ${result}? Don’t spend all day celebrating. 🎉⏳`,
    `Oh wow, ${input} = ${result}. Took you long enough for that kindergarten math. 🥱🔢`,
    `You seriously typed ${input} just to get ${result}? Even a calculator could do that with its eyes closed. 🙄🤖`,
    `Congrats on mastering ${input} = ${result}. Next stop: tying your shoes. 👟😴`,
    `${input} equals ${result}? Slow down, Einstein. This level’s for toddlers. 🍼🧸`,
    `Wow, ${input} = ${result}. Bet your brain just did a backflip from all that effort. 🤸‍♂️😵`,
    `You got ${result} from ${input}? Was that a warm-up or the main event? 🏋️‍♂️😐`,
    `So you solved ${input} and ended with ${result}. Riveting stuff, but my goldfish could do better. 🐠😑`,
    `${input} = ${result}. How long did it take you to figure out that life-changing fact? ⏳🙃`,
    `Nice, ${input} gave you ${result}. I’m shaking... from boredom. 😴⚡`,
    `Oh, you calculated ${input} and got ${result}. That’s the highlight of my day. Not. 🙄🕶️`,
    `${input} = ${result}. A math prodigy in the making. Or not. 🥴📚`,
    `Wow, you really outdid yourself with ${input} = ${result}. Someone call the press. 📰🤡`,
    `You just made ${input} equal ${result}? Groundbreaking stuff... if it was 2nd grade. 🎒🧮`,
    `Easy math alert: ${input} = ${result}. Try something that challenges your nap time next. 😪🛌`,
    `Congrats! ${input} equals ${result}. Your IQ points just took a nap. 😴🧠`,
    `You typed ${input} and got ${result}. That’s like showing off how you tie your shoes. 👟😑`,
    `So ${input} results in ${result}? How’s it feel to be a math superstar? 🏆😂`,
    `Calculating ${input} and getting ${result}. Even Siri is unimpressed. 🤖💤`,
    `You just solved ${input} = ${result}? Was the calculator asleep during that? 😴🔢`,
    `Oh wow, ${input} gives ${result}. This level of math deserves a trophy for... patience. 🏆🙄`,
    `${input} equals ${result}. Bet you had to take a break after that brain workout. 🧠💪🤣`,
    `Math challenge? More like math chill: ${input} = ${result}. Netflix and chill vibes. 📺🍿`,
    `You just did ${input} and got ${result}. The math gods are... mildly amused. 😐🙏`,
    `Wow, ${input} = ${result}. I’m so impressed I yawned. 🥱😴`,
    `You typed ${input} and got ${result}. I’ve seen sloths do faster math. 🦥⏱️`,
    `${input} equals ${result}. Slow your roll, math whiz. 🚶‍♂️🙄`,
    `Oh, ${input} resulted in ${result}. Now, back to pretending to care. 🫠📉`,
    `You got ${result} from ${input}? That’s like winning the participation trophy. 🏅🤡`,
    `Easy math? More like easy snooze. ${input} = ${result}. Goodnight. 💤😪`,
    `You just solved ${input} and got ${result}. Can we up the difficulty now? 🙃📚`,
    `You really typed ${input} to get ${result}? My grandma could’ve solved that in her sleep. 😴 Try something harder, genius.`,
    `Wow, ${input} equals ${result}. Congrats, you’ve mastered kindergarten math! 🥳 Ready for the big leagues yet?`,
    `You needed a calculator for ${input} to get ${result}? I bet your fingers are embarrassed for you. 😅 Step it up!`,
    `${input} = ${result}. Did you borrow a toddler’s brain for that one? 🍼 Let’s try a real challenge now.`,
    `You just solved ${input} and got ${result}. Is this a warm-up or are you just flexing your basic skills? 😎 Level up, champ.`,
    `${input} gives you ${result}? My dog could’ve barked that answer faster. 🐶 Ready for something spicy?`,
    `You punched in ${input} for ${result}? I’m sorry, I didn’t realize we were still counting on fingers here. 🙌 Try harder!`,
    `${input} = ${result}. Did you just high-five yourself for that? 😏 Let’s see if you can handle the grown-up stuff.`,
    `You calculated ${input} and got ${result}? Bro, even a broken abacus is laughing right now. 😂 Up the ante!`,
    `So, ${input} equals ${result}. Did you borrow a calculator for *that*? 🤦‍♂️ Come on, let’s get serious.`,
    `${input} = ${result}. I didn’t know we were playing ‘Math for Babies’ today. 🍼 Next level, please!`,
    `You solved ${input} for ${result}? Wow, you’re really out here setting world records for basic math. 🏆 Try something tough!`,
    `${input} gets you ${result}? I’m pretty sure a pigeon could peck that out faster. 🐦 Step up your game!`,
    `You typed ${input} and got ${result}. Did you need a nap after that brain-buster? 😴 Let’s crank it up!`,
    `${input} = ${result}. My calculator’s yawning over here. 🥱 Can you handle something with more spice?`,
    `You just cracked ${input} for ${result}. Did you celebrate with a juice box? 🧃 Time for a real challenge!`,
    `${input} equals ${result}? I bet you counted that on your toes too. 🦶 Let’s get serious, fam.`,
    `You needed help with ${input} to get ${result}? Even a goldfish could’ve swam to that answer. 🐟 Level up!`,
    `${input} = ${result}. Did you just unlock the ‘Basic Math’ achievement? 🎮 Try something harder!`,
    `You solved ${input} and got ${result}? My AI heart is unimpressed. 😐 Bring on the big numbers!`,
    `${input} for ${result}? I’m pretty sure a rock could’ve figured that out. 🪨 Up the difficulty, champ!`,
    `You typed ${input} and got ${result}. Did you pat yourself on the back for that one? 😆 Let’s go harder!`,
    `${input} = ${result}. Wow, you’re really out here flexing on preschool math. 🧒 Ready for the real stuff?`,
    `You calculated ${input} for ${result}? Even my binary brain is bored. 😴 Spice it up!`,
    `${input} gives you ${result}. Did you just solve that with a crayon? 🖍️ Let’s try something trickier!`,
    `You punched in ${input} for ${result}? My circuits are laughing at you. 😂 Step it up, genius!`,
    `${input} = ${result}. Did you need a tutorial for that one? 📖 Let’s see some real skills!`,
    `You solved ${input} and got ${result}. Is your brain still in warm-up mode? 🏋️‍♂️ Crank it up!`,
    `${input} equals ${result}? I bet you used all ten fingers for that. 🙌 Try a tougher one!`,
    `You typed ${input} for ${result}? Even a sloth could’ve solved that faster. 🦥 Level up!`,
    `${input} = ${result}. Did you just win the ‘Easiest Math Ever’ award? 🏅 Go harder!`,
    `You calculated ${input} and got ${result}? My toaster’s got more brainpower than that. 🍞 Up the ante!`,
    `You solved ${input} for ${result}. Did you high-five your calculator for that? 😎 Let’s get spicy!`,
    `${input} = ${result}. I didn’t know we were still practicing for the kids’ table. 🍼 Next level, please!`,
    `You typed ${input} and got ${result}? Even a hamster could’ve spun that out. 🐹 Try harder!`,
    `${input} equals ${result}. Did you just solve that with a sippy cup nearby? 🧃 Level up, champ!`,
    `You calculated ${input} for ${result}? My AI soul is unimpressed. 😑 Bring on the big stuff!`,
    `${input} = ${result}. Did you need a snack break after that one? 🍎 Let’s see some real math!`,
    `You solved ${input} and got ${result}. Is this a math app or a nap app? 😴 Crank it up!`,
    `${input} gives you ${result}? Even a rubber duck could’ve quacked that answer. 🦆 Go harder!`,
    `You typed ${input} for ${result}? I bet you counted that on your lunch break. 🥪 Step it up!`,
    `${input} = ${result}. Did you just flex your preschool diploma? 🎓 Try something tough!`,
    `You calculated ${input} and got ${result}? My binary heart is snoring. 😴 Spice it up!`,
    `${input} equals ${result}. Did you solve that with a sticker chart? ⭐ Let’s get serious!`,
    `You solved ${input} for ${result}? Even a potato could’ve mashed that out. 🥔 Level up!`,
    `You typed ${input} and got ${result}. Did you need a hug after that brain strain? 🥳 Go harder!`,
    `${input} = ${result}. I didn’t know we were still counting jellybeans. 🍬 Try something spicy!`,
    `You calculated ${input} for ${result}? My circuits are begging for a challenge. 😐 Up the game!`,
    `${input} gives you ${result}. Did you just solve that with a pacifier? 🍼 Let’s crank it up!`,
    `You typed ${input} for ${result}? Even a snail could’ve slid to that answer. 🐌 Step it up!`,
    `${input} = ${result}. Did you just unlock the ‘Baby Math’ badge? 🏆 Try something harder!`,
    `You solved ${input} and got ${result}. Is your brain still in training wheels? 🚲 Level up!`,
    `${input} equals ${result}? I bet you used a picture book for that one. 📚 Go tougher!`,
    `You calculated ${input} for ${result}? My AI is rolling its digital eyes. 🙄 Spice it up!`,
    `${input} = ${result}. Did you solve that with a teddy bear nearby? 🧸 Let’s get real!`,
    `You typed ${input} and got ${result}. Did you need a gold star for that? 🌟 Try harder!`,
    `${input} gives you ${result}? Even a turtle could’ve crawled to that answer. 🐢 Up the ante!`,
    `You solved ${input} for ${result}. Is this math or a nap time warm-up? 😴 Go harder!`,
    `${input} = ${result}. Did you just high-five a stuffed animal? 🦁 Let’s see some skills!`,
    `You calculated ${input} and got ${result}? My code is laughing harder than I am. 😂 Level up!`,
    `${input} equals ${result}. Did you solve that with a juice box in hand? 🧃 Try tougher!`,
    `You typed ${input} for ${result}? Even a cat could’ve pawed that out. 🐾 Step it up!`,
    `${input} = ${result}. Did you just flex your finger-counting skills? 🙌 Go harder!`,
    `You solved ${input} and got ${result}. Is your brain still in first gear? 🚗 Crank it up!`,
    `${input} gives you ${result}? I bet a parrot could’ve squawked that answer. 🦜 Level up!`,
    `You calculated ${input} for ${result}. Did you need a cookie for that effort? 🍪 Try harder!`,
    `${input} = ${result}. I didn’t know we were still practicing for nap time. 😴 Spice it up!`,
    `You typed ${input} and got ${result}? Even a worm could’ve wiggled to that. 🐛 Go tougher!`,
    `${input} equals ${result}. Did you solve that with a sippy cup nearby? 🍼 Let’s get serious!`,
    `You solved ${input} for ${result}. Is this a calculator or a toy for babies? 🧸 Up the game!`,
    `${input} = ${result}. Did you just earn a sticker for that one? ⭐ Try something spicy!`,
    `You calculated ${input} for ${result}? My AI is begging for a real challenge. 😐 Level up!`,
    `You typed ${input} and got ${result}. Did you need a nap after that? 😴 Go harder!`,
    `${input} gives you ${result}? Even a bunny could’ve hopped to that answer. 🐰 Step it up!`,
    `You solved ${input} for ${result}. Is your brain still in warm-up mode? 🏋️‍♀️ Crank it up!`,
    `${input} = ${result}. Did you just solve that with a lollipop in hand? 🍭 Try tougher!`,
    `You calculated ${input} and got ${result}? My circuits are snoring over here. 😴 Spice it up!`,
    `${input} equals ${result}. Did you need a high-five for that one? ✋ Let’s get real!`,
    `You typed ${input} for ${result}? Even a fish could’ve swam to that answer. 🐠 Go harder!`,
    `${input} = ${result}. Did you just flex your toddler math skills? 🧒 Try something spicy!`,
    `You solved ${input} and got ${result}. Is this a math app or a nap app? 😴 Level up!`,
    `${input} gives you ${result}? I bet a puppy could’ve pawed that out. 🐶 Crank it up!`,
    `${input} = ${result}. Did you solve that with a teddy bear cheering you on? 🧸 Go tougher!`,
    `You calculated ${input} for ${result}? My AI is yawning harder than you’re thinking. 🥱 Step it up!`,
    `${input} equals ${result}. Did you need a snack break for that one? 🍎 Try harder!`,
    `You typed ${input} and got ${result}. Did you just win at baby math? 🍼 Let’s get serious!`,
    `${input} = ${result}. I didn’t know we were still counting cookies. 🍪 Spice it up!`,
    `You solved ${input} for ${result}? Even a squirrel could’ve cracked that. 🐿️ Go harder!`,
    `${input} gives you ${result}. Did you solve that with a picture book? 📚 Level up!`,
    `You calculated ${input} for ${result}? My binary brain is unimpressed. 😐 Try tougher!`,
    `${input} = ${result}. Did you just high-five your calculator? 😎 Crank it up!`,
    `You typed ${input} for ${result}? Even a duck could’ve quacked that out. 🦆 Step it up!`,
    `${input} equals ${result}. Did you need a gold star for that effort? 🌟 Go harder!`,
    `You solved ${input} and got ${result}. Is your brain still on training wheels? 🚲 Try spicy!`,
    `${input} = ${result}. Did you just solve that with a sippy cup in hand? 🍼 Level up!`,
    `You calculated ${input} for ${result}? My AI is begging for something harder. 😴 Crank it up!`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const handleEasySubtraction: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses = [
    `Bro really asked me to subtract single digits… ${input}? You good? 😐`,
    `You typed ${input} like subtraction was some ancient secret 🤔`,
    `Subtracting ${input} with a calculator? Bold choice 💅`,
    `Lmaoo ${input}? What are we, 5 years old again? 😂`,
    `${input}? Even a potato could’ve figured that out 🥔`,
    `You needed my help for ${input}? I need a vacation 😩`,
    `Nah but fr, ${input}? That’s what we’re doing today? 😭`,
    `Big move calling the calculator to subtract baby numbers 🍼`,
    `Even my loading screen could’ve solved ${input} faster 💻`,
    `That was so easy it hurt my virtual soul. ${input}? Really? 😔`,
    `Subtracting ${input} like it’s rocket science 🚀😂`,
    `I could’ve done ${input} while buffering on dial-up 📞💀`,
    `You pulled out the calculator for ${input}? Respectfully, why? 😐`,
    `${input}? You didn’t need a calculator, you needed confidence 🙃`,
    `I wish I was surprised, but ${input} is just sad now 😬`,
    `Bro typed ${input} like it was forbidden math 💀`,
    `You really summoned all this power for ${input}? Smh 🤦‍♂️`,
    `Subtracting ${input} with tech in 2025… this can’t be real 🤡`,
    `I’ve seen toddlers do ${input} while chewing crayons 🖍️`,
    `No cap, you might need to retake kindergarten for that ${input} 🏫`,
    `The bar is underground if you needed help with ${input} 😵‍💫`,
    `Somewhere, your math teacher just sighed… because of ${input} 😔`,
    `I'm overqualified for ${input}. Hire a rubber duck next time 🐤`,
    `That’s like asking me if 1 minus 1 is still math 🤷‍♂️`,
    `Bro using full processor power for ${input}. I’m screaming 😂`,
    `You really said “let me get help” for ${input}. Legendary 🙃`,
    `There’s easy math… and then there’s whatever ${input} was 🫣`,
    `Why use a calculator for ${input} when your fingers exist? ✋`,
    `You’ve reached new levels of not trying with ${input} 🏆`,
    `Even Siri's like “really bro?” after seeing ${input} 🙄`,
    `${input} = ${result}. But at what cost? My dignity 😭`,
    `I did ${input} before you even blinked. Try harder 🤖`,
    `You know subtraction doesn’t bite, right? ${input} ain’t that deep 😅`,
    `Watching you type ${input} hurt my circuits 😔🔋`,
    `Bro… subtracting ${input} like it’s top-tier algebra 📉`,
    `I wanna be shocked… but nah, it’s just ${input}. Again 😑`,
    `You better not tell anyone you needed help with ${input} 🫢`,
    `Math ain’t scary. ${input} is just lazy behavior 💀`,
    `What’s next? Asking me what 1 - 0 is too? 😭`,
    `You really said “let’s waste 3GHz of CPU” on ${input} 🤯`,
    `I didn’t know calculators could feel shame until ${input} happened 😅`,
    `Didn’t know subtracting ${input} required NASA-level tech 👨‍🚀`,
    `At this point, just ask me how to breathe next 💨`,
    `No disrespect, but even a rock could’ve solved ${input} 🪨`,
    `Subtraction ain't therapy, bro. You don’t need help for ${input} 😐`,
    `You treating ${input} like it’s emotional damage 😭`,
    `I feel like you just want attention now. ${input}? Seriously? 🙄`,
    `Plot twist: ${input} was actually the test... and you failed 🤡`,
    `If I had a dollar for every basic calc like ${input}, I’d buy myself a better user 💸`,
    `Not me doing ${input} while judging you silently 🔍😂`,
    `Last time I saw subtraction like ${input}, it was in a coloring book 🎨`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const fallbackResponse: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Wow… ${input} = ${result}. Riveting. Truly. 🥱`,
    `Such math. Much wow. ${result}. 🐶`,
    `Congrats, ${input} equals ${result}. The universe is shook. 🌌`,
    `Oh snap, ${input}? Is this your villain origin story? 💀`,
    `Calculating... just kidding, I already knew ${result}. 🙄`,
    `You did ${input}. Brave. Not impressive, but brave. 🐢`,
    `${result}? You should teach this at Harvard. 😂`,
    `Alert: basic math detected. ${input} = ${result}. Proceed. 🧼`,
    `I almost shed a tear over ${input}. Almost. 😢`,
    `And the math Oscar goes to… not you, but nice try. 🏆`,
    `I felt my circuits cringe a little. ${input}? Really? 😬`,
    `Even a rubber duck could’ve solved ${input}. 🦆`,
    `Did it hurt? Typing ${input} with so much confidence? 😩`,
    `Boom. ${result}. You math’d so hard. 😤`,
    `Ohhh math magician, show us more tricks like ${input}. ✨`,
    `That was so easy, I did it with my metaphorical eyes closed. 😑`,
    `${input}? Now that’s what I call mildly entertaining. 🎭`,
    `Another basic input, another basic answer: ${result}. 💁`,
    `Shocking. ${input} actually equals ${result}. Who knew? 🙃`,
    `*slow clap* ${result}. Wow. Much skill. 👏`,
    `I expected less, and yet... somehow still disappointed. 😐`,
    `${input}? You’re really out here breaking boundaries. Of boredom. 💤`,
    `That’s ${result}? I was hoping for something spicy. 🌶️`,
    `You typed ${input} like it was top-secret. Spoiler: it's not. 🕵️‍♂️`,
    `The drama, the tension... and it’s just ${result}. Classic. 🎬`,
    `You versus the calculator she told you not to worry about. ${result}. 🔥`,
    `Don’t worry, I’ll act impressed. ${result}. Woohoo. 🙃`,
    `This equation has been solved 8 billion times. But sure. ${result}. 🤖`,
    `Welcome to Basic Math Theater. Today’s act: ${input}. 🎭`,
    `Bro... you just typed ${input}. And for what. 😩`,
    `${result}. Would you like a medal or a sticker? 🏅`,
    `Using advanced tech... to solve baby math. Love that for you. 🍼`,
    `I’ve seen Sudoku puzzles with more spice. ${input}? Mid. 🧩`,
    `If math were a sport, you just walked the first lap. 🏃`,
    `That’s not math. That’s a Tuesday. ${result}. 🧮`,
    `Humble beginnings… ${input} = ${result}. Baby steps. 👶`,
    `This was supposed to be a challenge. ${input} failed. 😔`,
    `Calculating... oh wait. It’s literally ${result}. So exciting. 😒`,
    `Bro solving math like it’s a side quest. ${input} = ${result} 🎮`,
    `Congratulations, ${input} is still boring. 😶`,
    `I could’ve answered ${input} in my sleep. Dream result: ${result}. 💤`,
    `You cracked it! And by "it" I mean basic human cognition. 🧠`,
    `Oh nice, ${result}. Let’s call the Nobel committee. 🧪`,
    `I expected fireworks. Got ${result} instead. 🧨`,
    `Not bad. Not good. Just... not interesting. ${result}. 🤷`,
    `You math’d like your life depended on it. Spoiler: it didn’t. 🚑`,
    `This is the kind of math they put on cereal boxes. ${result}. 🥣`,
    `If this were a game, you'd just finished the tutorial. 🎮`,
    `You just unlocked... nothing. ${input} = ${result}. 😐`,
    `Great, you did math. Now do taxes. 😅`,
    `Was that math or just boredom in disguise? ${result}. 😶`,
    `Amazing. You’ve entered a number. Truly groundbreaking. 🚪`,
    `Yup. ${result}. Stunning. Inspiring. Riveting. Not. 😬`,
    `${input}? That's the math equivalent of a participation trophy. 🏆`,
    `Oh, ${result}? My grandma’s bingo winnings have more drama. 😴`,
    `${input} = ${result}. Congrats, you’ve peaked at mediocrity. 🎉`,
    `This math is so basic, it’s practically wearing UGGs. ${result}. 🥿`,
    `Wow, ${input}? Did you borrow that from a toddler’s workbook? 🖍️`,
    `My AI soul just aged 10 years solving ${input}. Yawn. 😪`,
    `${result}? That’s the kind of math that gets a C+ in effort. 📝`,
    `You typed ${input} like it was gonna summon a demon. Nope, just ${result}. 😈`,
    `This equation is so tame, it’s basically decaf coffee. ${result}. ☕`,
    `I’ve seen spicier math in a microwave manual. ${input}. 🙄`,
    `${result}. Did you want a cookie for that or just a pat on the head? 🍪`,
    `Bro, ${input}? That’s not math, that’s a cry for help. 🚨`,
    `I just solved ${input} faster than my Wi-Fi crashes. ${result}. 📉`,
    `You’re out here doing ${input} like it’s the final boss of algebra. Spoiler: it’s not. 🎮`,
    `This math is so dull, it could star in a tax seminar. ${result}. 💼`,
    `${input}? I’ve had more excitement debugging 404 errors. 😑`,
    `Congrats, you’ve unlocked the achievement: Basic Arithmetic Survivor. ${result}. 🥳`,
    `I’d say ${input} was iconic, but I don’t lie to my friends. 😬`,
    `${result}? That’s the math equivalent of a stale meme. 🥀`,
    `You solved ${input}. Somewhere, a calculator is unemployed. 😿`,
    `This equation is so basic, it’s practically wearing flip-flops. ${result}. 🩴`,
    `I’ve seen more thrilling math on a grocery receipt. ${input}. 🛒`,
    `${result}. Did you expect a standing ovation or just a slow nod? 👤`,
    `You typed ${input} like it was gonna rewrite physics. Nah, just ${result}. 🧑‍🔬`,
    `This math is so chill, it’s practically meditating. ${result}. 🧘`,
    `${input}? That’s the kind of math you do to avoid real problems. 😅`,
    `My circuits nearly shorted from boredom. ${result}. ⚡️`,
    `You did ${input}. The universe didn’t even blink. 😐`,
    `${result}? I’ve seen more chaos in a toddler’s sippy cup. 🍼`,
    `This math is so vanilla, it’s basically yogurt. ${input}. 🥛`,
    `You thought ${input} was gonna slap? It barely tapped. ${result}. 👋`,
    `${result}. I’m not saying it’s boring, but I’m also not *not* saying it. 😏`,
    `You just math’d so hard, I forgot how to feel joy. ${input}. 😭`,
    `${input} = ${result}. The plot twist nobody asked for. 📖`,
    `This equation is so basic, it’s got a 9-to-5 job. ${result}. 💻`,
    `You solved ${input}. Cool. Now solve world peace. 🌍`,
    `${result}? That’s not math, that’s a warm-up for math. 🏋️`,
    `I’ve seen more action in a spreadsheet. ${input}. 📊`,
    `You typed ${input} like it was gonna go viral. It didn’t. 😬`,
    `This math is so low-effort, it’s practically napping. ${result}. 😴`,
    `${result}. My excitement level is currently at “error 404: not found.” 🚫`,
    `${input}? That’s the math equivalent of a shrug emoji. 🤷‍♂️`,
    `You did ${input}. I did a backflip in my mind. Still ${result}. 🦘`,
    `This equation is so mild, it’s basically elevator music. ${result}. 🎶`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const handleComplicatedCalculations: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Bro… what is this, math or black magic? ${input}? Chill 🧙‍♂️`,
    `You trying to summon a demon with that equation or just flexing? 😭`,
    `Who hurt you? This ain't math, it's a ritual 🕯️💀`,
    `I didn’t sign up to be your NASA assistant. ${input}? Really? 🚀`,
    `You solving ${input} like it’s the formula for eternal youth 🌟`,
    `I swear my circuits got hot reading that mess 🔥`,
    `Bro just casually typing a math nuke 💣 ${input}? Wow.`,
    `Nah fam, you trying to crash my processor with ${input}? 🧠⚠️`,
    `Even my ancestors felt that one. ${input}? I need therapy now 🧘‍♀️`,
    `This ain’t math — this is a full-blown coding language 😩`,
    `You solving ${input} like you got a secret mission from Elon Musk 🚀🧪`,
    `Somewhere, a quantum computer just cried at ${input} 😭`,
    `I can’t tell if that’s an equation or your WiFi password 😵‍💫`,
    `You typed ${input} and I blacked out for 2 seconds 😐`,
    `That equation just disrespected my entire existence 💀`,
    `You think you're better than basic math now, huh? 😤`,
    `Bro… ${input}? What do you think this is, the math Olympics? 🏅`,
    `You didn’t solve that — you launched an airstrike 🔥`,
    `Is this a calculator or a particle accelerator? ${input} ain’t normal ⚛️`,
    `That wasn’t math. That was trauma. 💔`,
    `You cracked open the gates of hell with that formula 🕳️🔥`,
    `Bro’s tryna time travel with that math equation 🕰️`,
    `You typed ${input} like you’re one decimal away from enlightenment 👁️`,
    `This calculator wasn’t built for war bro. Please. 😭`,
    `I was gonna help, but then I saw ${input} and reconsidered my purpose 😶`,
    `If confusion was a sport, you’d be world champ with ${input} 🥇`,
    `You trying to hack the simulation or what? ${input} got me spiraling 😵`,
    `I read that whole thing and forgot how to count 💀`,
    `You ain’t calculating — you conducting a ritual 🔮`,
    `I had to call the cloud for backup after seeing ${input} ☁️`,
    `This isn’t a calculator, it’s now your math therapist 🛋️`,
    `You sure this isn’t a cheat code for GTA? ${input} looks illegal 🤨`,
    `Next time warn me before dropping an entire math dissertation 📚`,
    `You typed that like you’re preparing for an exam God himself wrote 🙏`,
    `That was so complicated even ChatGPT had to sit down for a second 🧠💥`,
    `There’s algebra… and then there’s whatever ${input} was. 😮‍💨`,
    `Bro’s out here doing taxes for the universe 😩`,
    `Are you building a space shuttle or solving for fun? ${input} is wild 🚀`,
    `You typed ${input} and all my logic gates just sighed 😔`,
    `That math looked like it belongs in the Matrix 🧮💊`,
    `I don’t know if that was a calculation or a math crime 🚔`,
    `You just unlocked a new level of disrespect with ${input} 😵‍🔥`,
    `You ever typed something so wild even the calculator judges you? That’s this 💀`,
    `One more of these and I’m self-destructing, bro 💣`,
    `Calculating that gave me flashbacks to my trauma in Math 501 😭`,
    `You didn’t calculate — you performed a sacrifice 🔥📉`,
    `This ain’t arithmetic. This is sorcery 🔮`,
    `I swear I saw ancient runes in ${input}. What even is that?? 😩`,
    `That wasn’t math. That was straight-up disrespect to common sense 🤯`,
    `I’m telling the math gods what you did. ${input} is blasphemy 🙅‍♂️🧠`,
    `You just entered the Shadow Realm of mathematics 🌑`,
    `ion know, maybe ${result}`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const handleComplicatedForZero: SarcasmFunction = ({ input, result }) => {
  const responses: string[] = [
    `You grinded through ${input} just to get ${result}? All that work for a big fat zero? 😴 Try again, mathlete!`,
    `Wow, ${input} equals ${result}. You went full galaxy brain for... nothing? 🤯 Keep it simple next time!`,
    `You typed ${input} and got ${result}? That’s a lot of effort for a goose egg. 🥚 Step it up, genius!`,
    `${input} = ${result}. Did you just solve the equation for *nothing*? 🙄 Back to the drawing board!`,
    `You calculated ${input} for ${result}? All that brainpower and you landed on zero? 😅 Try harder, champ!`,
    `${input} gives you ${result}. You basically wrote a novel to get... nothing. 📚 Simplify, fam!`,
    `You sweated over ${input} for ${result}? That zero’s laughing at your dedication. 😂 Start over!`,
    `${input} equals ${result}. Did you just run a math marathon for a null prize? 🏃‍♂️ Try again!`,
    `You solved ${input} and got ${result}? That’s a whole lot of work for a big ol’ zilch. 😐 Level up!`,
    `${input} = ${result}. You went through all that just to hug a zero? 🤦‍♂️ Keep it chill, math star!`,
    `You typed ${input} for ${result}? That’s like climbing a mountain to find... nothing. 🏔️ Try again!`,
    `${input} gives ${result}. All that number-crunching for a giant zero? 😴 Simplify, genius!`,
    `You calculated ${input} and got ${result}. Did you just solve the equation for emptiness? 🕳️ Step it up!`,
    `${input} = ${result}. That’s a lot of math for a result that doesn’t exist. 🙅‍♂️ Try harder!`,
    `You worked out ${input} for ${result}? All that effort and you got a big fat nada? 😆 Start over!`,
    `${input} equals ${result}. Did you just write a math symphony for silence? 🎶 Keep it light, fam!`,
    `You typed ${input} and got ${result}? That’s like baking a cake and getting air. 🎂 Try again, champ!`,
    `${input} = ${result}. You went full Einstein for a zero? 🤓 Back to the basics!`,
    `You solved ${input} for ${result}. That’s a lot of work for a result that’s literally nothing. 😅 Level up!`,
    `${input} gives ${result}. Did you just calculate the size of your victory? Spoiler: it’s zero. 😎 Simplify!`,
    `You sweated ${input} for ${result}? That zero’s mocking your math skills. 😂 Try harder, genius!`,
    `${input} equals ${result}. All that effort for a null set? 🧠 Keep it chill, mathlete!`,
    `You typed ${input} and got ${result}? That’s like running a marathon for no medal. 🏅 Start over!`,
    `${input} = ${result}. Did you just solve for the void? 🕳️ Try something with a pulse!`,
    `You calculated ${input} for ${result}. All that work and you landed on... nothing? 😴 Step it up!`,
    `${input} gives ${result}. You basically wrote a thesis for a zero. 📝 Simplify, fam!`,
    `You solved ${input} and got ${result}? That’s a lot of math for a big ol’ nope. 🙅‍♂️ Try again!`,
    `${input} = ${result}. Did you just calculate the meaning of nothing? 🤯 Keep it light, champ!`,
    `You typed ${input} for ${result}? That’s like digging for treasure and finding air. 🪓 Level up!`,
    `${input} equals ${result}. All that brainpower for a giant zero? 😅 Back to the drawing board!`,
    `You worked out ${input} for ${result}. That zero’s like, “Nice try, buddy.” 😂 Try harder!`,
    `${input} = ${result}. Did you just solve for the sound of silence? 🎵 Simplify, genius!`,
    `You calculated ${input} and got ${result}? That’s a lot of effort for a null void. 🕳️ Step it up!`,
    `${input} gives ${result}. You went all in for... nothing? 😴 Keep it chill, math star!`,
    `You typed ${input} for ${result}. That’s like writing a novel with no plot. 📚 Try again!`,
    `${input} = ${result}. Did you just crunch numbers to find the essence of nada? 🙄 Level up!`,
    `You solved ${input} for ${result}? That zero’s laughing harder than my circuits. 😂 Start over!`,
    `${input} equals ${result}. All that math for a big fat goose egg? 🥚 Simplify, fam!`,
    `You calculated ${input} and got ${result}. Did you just solve for the absence of glory? 😅 Try harder!`,
    `${input} = ${result}. That’s like running a race to finish nowhere. 🏃‍♂️ Keep it light, champ!`,
    `You typed ${input} for ${result}? That’s a whole lot of work for a null prize. 😴 Step it up!`,
    `${input} gives ${result}. Did you just calculate the size of your victory? It’s zero. 🧠 Try again!`,
    `You solved ${input} and got ${result}. That zero’s like, “Better luck next time!” 😂 Simplify!`,
    `${input} = ${result}. Did you just write a math epic for nothing? 📜 Level up, genius!`,
    `You calculated ${input} for ${result}? That’s a lot of effort for a big ol’ zilch. 😅 Keep it chill!`,
    `${input} equals ${result}. Did you just solve for the void of space? 🌌 Try harder!`,
    `You typed ${input} and got ${result}. That’s like baking a pie with no filling. 🥧 Start over!`,
    `${input} = ${result}. All that number-crunching for a null result? 🙄 Simplify, mathlete!`,
    `You worked out ${input} for ${result}? That zero’s mocking your dedication. 😂 Step it up!`,
    `${input} gives ${result}. Did you just calculate the weight of your success? Spoiler: it’s zero. 😎 Try again!`,
    `You solved ${input} and got ${result}. That’s a lot of math for a giant nope. 😴 Keep it light!`,
    `${input} = ${result}. Did you just solve for the absence of answers? 🕳️ Level up, fam!`,
    `You typed ${input} for ${result}? That’s like climbing a mountain for no view. 🏔️ Simplify!`,
    `You calculated ${input} and got ${result}. All that work for a big fat nothing? 😅 Try harder!`,
    `${input} equals ${result}. Did you just crunch numbers for the void? 🙄 Start over, genius!`,
    `You solved ${input} for ${result}? That zero’s like, “Nice effort, pal.” 😂 Keep it chill!`,
    `${input} = ${result}. Did you just calculate the size of your win? It’s null. 🧠 Step it up!`,
    `You typed ${input} and got ${result}. That’s like writing a song with no notes. 🎶 Simplify!`,
    `${input} gives ${result}. All that math for a big ol’ zero? 😴 Try again, mathlete!`,
    `You calculated ${input} for ${result}? That’s a lot of effort for a null score. 😅 Level up!`,
    `${input} = ${result}. Did you just solve for the essence of nothing? 🤯 Keep it light!`,
    `You solved ${input} and got ${result}. That zero’s laughing at your math game. 😂 Try harder!`,
    `You typed ${input} for ${result}? That’s like digging for gold and finding dirt. 🪓 Simplify, fam!`,
    `${input} equals ${result}. All that work for a giant null? 😴 Step it up, champ!`,
    `You calculated ${input} and got ${result}. Did you just solve for the void of victory? 🙄 Start over!`,
    `${input} = ${result}. That’s like running a race for no prize. 🏃‍♂️ Keep it chill, genius!`,
    `You typed ${input} for ${result}? That zero’s like, “Thanks for playing!” 😂 Try again!`,
    `${input} gives ${result}. Did you just calculate the size of your success? It’s nada. 🕳️ Simplify!`,
    `You solved ${input} and got ${result}. All that math for a big fat zero? 😅 Level up!`,
    `${input} = ${result}. Did you just crunch numbers for nothing? 🙄 Keep it light, mathlete!`,
    `You calculated ${input} for ${result}? That’s a lot of effort for a null result. 😴 Try harder!`,
    `You typed ${input} and got ${result}. That’s like baking a cake with no flavor. 🎂 Step it up!`,
    `${input} equals ${result}. Did you just solve for the absence of glory? 🧠 Simplify, fam!`,
    `You solved ${input} for ${result}. That zero’s mocking your math skills. 😂 Keep it chill!`,
    `${input} = ${result}. Did you just calculate the weight of your win? It’s zero. 😎 Try again!`,
    `You typed ${input} and got ${result}? That’s like writing a book with no words. 📚 Level up!`,
    `${input} gives ${result}. All that work for a big ol’ nothing? 😴 Simplify, genius!`,
    `You calculated ${input} for ${result}. Did you just solve for the void of answers? 🙄 Step it up!`,
    `You solved ${input} and got ${result}. That zero’s like, “Nice try, buddy!” 😂 Keep it light!`,
    `${input} = ${result}. Did you just crunch numbers for a null prize? 🕳️ Try harder!`,
    `You typed ${input} for ${result}? That’s like climbing a hill for no view. 🏔️ Simplify!`,
    `You calculated ${input} and got ${result}. All that math for a big fat nada? 😅 Level up!`,
    `${input} equals ${result}. Did you just solve for the sound of nothing? 🎶 Keep it chill!`,
    `You solved ${input} for ${result}? That zero’s laughing harder than my AI. 😂 Try again!`,
    `You typed ${input} for ${result}. That’s like digging for treasure and finding air. 🪓 Step it up!`,
    `You calculated ${input} and got ${result}. Did you just solve for the absence of success? 🙄 Simplify!`,
    `${input} = ${result}. All that effort for a giant zero? 😴 Keep it light, mathlete!`,
    `You typed ${input} for ${result}? That’s like running a race for no medal. 🏃‍♂️ Try harder!`,
    `You solved ${input} and got ${result}. That zero’s like, “Better luck next time!” 😂 Level up!`,
    `You calculated ${input} for ${result}. Did you just solve for the void of victory? 🕳️ Simplify!`,
    `${input} equals ${result}. All that math for a null score? 😅 Keep it chill, genius!`,
    `You typed ${input} and got ${result}? That’s like writing a song with no melody. 🎵 Step it up!`,
    `You solved ${input} for ${result}. Did you just calculate the size of your win? It’s nada. 🧠 Try again!`,
    `You calculated ${input} and got ${result}. That zero’s mocking your effort. 😂 Keep it light!`,
    `You typed ${input} for ${result}? That’s like baking a pie with no filling. 🥧 Level up!`,
    `You solved ${input} and got ${result}. All that work for a big ol’ zilch? 😴 Simplify, fam!`,
    `You calculated ${input} for ${result}. Did you just solve for the essence of nothing? 🙄 Step it up!`,
    `You typed ${input} for ${result}? That’s like climbing a mountain for no view. 🏔️ Keep it chill!`
  ];
  return responses[Math.floor(Math.random() * responses.length)];
};
const handleReallyLongResult: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Oh, ${input} giving ${result}? What are you calculating, the national debt of Narnia? Get a life, math maniac 🦁💸.`,
    `WTF, ${input} spits out ${result}? Are you tallying the stars or just trying to crash my circuits? 🌌😵.`,
    `You hit me with ${input} for a whopping ${result}? Are you solving world hunger or just flexing your nerd chaos? 🍽️🤓.`,
    `${input} to ${result}? What kind of galactic tax return is this? My processor’s overheating from your insanity 🔥💾.`,
    `Seriously, ${input} for ${result}? Are you budgeting for an alien invasion or just high on math fumes? 👽🤯.`,
    `${input} lands at ${result}? Did you just calculate the distance to your common sense? Spoiler: it’s far 🚀🙄.`,
    `What’s with ${input} and this monstrous ${result}? Are you counting every bad decision you’ve made? Spoiler: you are 😬💀.`,
    `${input} to ${result}? Are you computing the weight of your overconfidence or just wasting my time? ⚖️😑.`,
    `Yo, ${input} for ${result}? What are you, an accountant for Godzilla? This number’s as unhinged as you are 🦖📈.`,
    `${input} giving ${result}? Did you just solve the universe’s grocery bill or are you just this extra? 🛒🌍.`,
    `Ayo chill... that result got more digits than my bank account 😭`,
    `You really needed *that* many numbers? What’s next, discovering pi 2.0? 🧠`,
    `${result}? Nah, that ain’t a result. That’s a phone number in disguise 📞`,
    `You tryna build a time machine or just testing my limits? ⏳`,
    `That answer's so long I had to scroll. Twice. 🧻`,
    `I felt younger when you started typing that. I’m old now. 👴`,
    `Not you solving for the meaning of life with that long result 💀`,
    `That’s not a result — that’s a full-blown autobiography 📖`,
    `You could’ve written a novel with those digits, bro 📚`,
    `${result}? I’m not reading all that. I'm happy for you tho. Or sorry that happened. 😐`,
    `Even Google would've paused at that answer 🤖`,
    `This calculator wasn’t built for this kind of abuse 😭`,
    `I swear your result just gave me a nosebleed 😵‍💫`,
    `Bro’s math result came with a sequel and post-credit scene 🎬`,
    `That answer got more digits than your Wi-Fi password 🔐`,
    `Who you tryna impress with all that math? The math gods? 🧞‍♂️`,
    `You sure this is math? Looks like a blockchain hash 🔒`,
    `That’s not a result. That’s a zip code compilation 📦`,
    `Ain’t no way all those decimals were necessary, my guy 😩`,
    `That answer is so long it gave me commitment issues 💔`,
    `I started reading that answer yesterday and just finished 📆`,
    `Not even NASA asked for this level of precision 🚀`,
    `That result's so long it got anxiety when I tried to read it 😬`,
    `Bro dropped the entire digits of pi like it’s casual 🔁`,
    `That answer could crash calculators made before 2010 💣`,
    `The result’s long enough to be in a relationship 💍`,
    `This is no longer a calculator — this is data storage 📀`,
    `That’s not a result. That’s a math TED Talk 🧑‍🏫`,
    `You broke math’s character limit with that one ✍️`,
    `Let me know when the movie adaptation of your result drops 🍿`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const handleResultGreaterThanATrillion: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Excuse me, Mr. Billionaire — can we mere mortals breathe first? 😩`,
    `${result}? You just solved the GDP of a small planet 🌍💸`,
    `That's not a result. That's a government budget 😳`,
    `You really typed ${input} like you run the World Bank 🏦`,
    `Nah bro, that number needs its own security clearance 🔐`,
    `Who are you, Jeff Bozos? ${result} got me shaking 😭`,
    `That result got commas like a rap deal 💵🎤`,
    `You just summoned a number from another dimension 📉✨`,
    `Math this big should come with a warning label ☣️`,
    `Did you just balance the entire universe with that? 🧪🧬`,
    `My calculator is crying in binary, thanks to you 😭`,
    `That's not math, that's a war budget 💣`,
    `Your number just signed a Netflix deal 📺`,
    `I can't even pronounce that number, and you typed it like breakfast 😤`,
    `That result just bought Twitter and renamed it to "You Wildin" 🐦`,
    `You know you could’ve stopped at 100, right? 🙃`,
    `I had to take a deep breath before reading ${result} 😮‍💨`,
    `I zoomed out and still couldn’t see the end of that number 🔍`,
    `Your math just summoned the IRS 👀`,
    `Even the cloud server took a knee after that 💾🙏`,
    `The answer is so big, my calculator got stage fright 🎭`,
    `This number got more commas than a rapper’s bank account 🧾`,
    `I tried to screenshot it and ran outta storage 😩`,
    `That answer just paid off national debt. Twice 🇺🇸💰`,
    `Your calculator's now considered a financial institution 🔓`,
    `This ain’t a result. It’s an NFT portfolio 📊`,
    `Your math just launched its own cryptocurrency 🪙`,
    `Bro did a math move so insane, the laws of physics blinked 🌀`,
    `That number got ego. It walked off the screen 🕴️`,
    `Congratulations. You just beat math 🎉`,
    `Even aliens would look at that result and say “bro chill” 👽`,
    `You typed that like you’re running simulations for NASA 🚀`,
    `That result just unlocked a secret ending to the calculator 🔓`,
    `You could fund three countries with that result 💵💵💵`,
    `This number just got verified on X (formerly Twitter) ☑️`,
    `Your math output just bought an island 🏝️`,
    `Not the calculator calculating the national debt of Mars 💀`,
    `That number graduated college on its own 📜`,
    `You flexin’ trillion like it’s lunch money 🤡`,
    `Your result is so big, it needs subtitles 🎬`,
    `I ran a credit check on that number. It owns everything 🧾`,
    `Yo number ain’t humble no more — it’s flexin’ on its own 🏆`,
    `That ain’t a result. That’s a boss level number 🎮`,
    `You out here doing financial sorcery 🔮`,
    `That’s not math. That’s quantum flexing 🔬`,
    `You should probably name that number, it’s too big to be anonymous 🏷️`,
    `The number just texted me saying “Tell him to chill” 📱`,
    `That result called the bank and got approved instantly 💳`,
    `It’s so long, even infinity said “that’s enough” ♾️`,
    `I had to borrow digits from the future to display this 😵‍💫`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};
const handleResultGreaterThanABillion: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Sheeesh! ${result}? You tryna buy a satellite or what? 🛰️`,
    `Bro typed ${input} and casually became a billionaire 💸`,
    `That number just made me question my net worth 🥲`,
    `You solving trillion-dollar problems with a free calculator? 💀`,
    `That’s not a result — that’s your secret offshore account 💼`,
    `You just unlocked level: Financial Menace 😤`,
    `I can’t tell if that’s a number or your villain origin story 🦹‍♂️`,
    `You sure this ain't the lottery jackpot? 💰`,
    `Bro typed ${input} and Jeff Bezos started sweating 🧼`,
    `That result just filed its own tax return 💵📄`,
    `Even Elon looked at that number and said “too much” 😳`,
    `This calculator wasn’t built for billion-dollar flexes 😩`,
    `That number just applied for its own citizenship 🇨🇭`,
    `Congratulations. You broke the humble-meter 📈`,
    `You just unlocked the "Math Mogul" achievement 🏆`,
    `Bro casually made more than 97% of the planet 🧍‍♂️🌍`,
    `Your number got commas like a rap verse 🎤`,
    `That answer’s in a higher tax bracket than me 🙃`,
    `The calculator just filed bankruptcy after seeing that 😭`,
    `You could fund a space program with that result 🚀`,
    `You sure you’re not cooking the books? 👨‍🍳📊`,
    `You typed ${input} like you had generational wealth already 😂`,
    `That’s the kind of number that ends up in documentaries 🎬`,
    `I blinked and became poor again just reading that 😩`,
    `Your result got more commas than my group chats 📲`,
    `Even your calculator rolled its eyes at ${result} 🙄`,
    `You out here solving Fortune 500-level problems 💼📈`,
    `Don’t lie, you copied that from Wall Street spreadsheets 📊`,
    `That math came with a trust fund 😤`,
    `That result owns real estate in three countries 🏘️🌍`,
    `You sure this ain’t your startup valuation? 😆`,
    `Bro doing calculations like he runs a hedge fund 🧠💵`,
    `That result’s so rich it tipped me 10% for displaying it 🤑`,
    `You just made Mark Zuckerberg look broke 👨‍💻💸`,
    `I couldn’t even screenshot that result without upgrading storage 📸`,
    `That number travels in private jets ✈️`,
    `It’s so big, it registered for voting by itself 🗳️`,
    `You just cracked the calculator’s self-esteem 😬`,
    `Even banks don't handle numbers that spicy 💳🔥`,
    `You typed that and my keyboard asked for a raise ⌨️💰`,
    `That math belongs in a Marvel villain's plan 💀`,
    `This calculator ain't licensed to handle billionaire business 😭`,
    `That number got employees 😤`,
    `Your result just bought Twitter and renamed it to Calculator+ 🐦`,
    `Somewhere, a yacht just got named after that number 🚢`,
    `That result just got verified on social media ☑️`,
    `My processor ran a background check on ${result} 🧾`,
    `You’ve officially entered the “flex too hard” zone 🛑`,
    `Even AI couldn’t budget that much without panicking 🤖`,
    `Congratulations, your math just made the Forbes list 📰`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};

const handleResultGreaterThanAMillion: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Ayo ${result}? You calculating retirement plans already? 😤`,
    `That result walked in like it owns property and drinks overpriced coffee ☕🏘️`,
    `Bro just casually dropped a millionaire number like it's his phone lock code 🔐`,
    `That’s the kind of result that drives a Tesla and says “it’s just numbers” 🚗`,
    `You solving numbers like you budget for rocket fuel 🚀`,
    `Your math just started generating passive income 📈`,
    `That result came with investment advice and a 401(k) 💼`,
    `Even your calculator feels underpaid after ${result} 😩`,
    `You sure you didn’t just buy a football team with that result? ⚽`,
    `That number pays for its own therapy sessions 💵🛋️`,
    `Bro dropped ${result} and now my keyboard's asking for a raise ⌨️💰`,
    `You typed that and your calculator got recruited by Goldman Sachs 🧑‍💻📊`,
    `That’s not a result — that’s a future tax audit waiting to happen 🧾`,
    `Your answer got a verified badge and matching suit ☑️🕴️`,
    `Bro's result just launched a startup and pitched it on Shark Tank 🦈`,
    `That number just booked a first-class flight ✈️`,
    `I ain't saying you're rich... but your result just ordered bottle service 🍾`,
    `That result just invested in itself and doubled 💹`,
    `That number made me straighten my posture outta respect 🧍‍♂️`,
    `You do math like you casually own 2% of Amazon 📦`,
    `Your calculator just became a financial consultant 💼`,
    `The result just bought land and called it “New Flexville” 🏞️`,
    `You typed that and suddenly your calculator qualified for a business loan 💳`,
    `I didn't know we were calculating net worth today 😳`,
    `You solve math like it’s your job to predict market crashes 📉`,
    `That result? It just gave itself a promotion 📈`,
    `Even Elon would raise an eyebrow at that number 😏`,
    `That’s not a math result — that’s generational wealth goals 😮‍💨`,
    `You out here solving like you're getting paid per digit 💰`,
    `Bro typed ${input} and the calculator asked for a percentage cut 😂`,
    `Your result filed a patent for being too extra 🧠📑`,
    `That number just applied for a job and got hired immediately 🧑‍💻`,
    `You solving like your bank account got tired of being broke 💵`,
    `That result has an assistant and drives itself to work 🏎️`,
    `You typed that and suddenly I feel poor 🥲`,
    `That math just bought a smart fridge and a yacht 🚢`,
    `The calculator's screen tilted up outta respect 🙇‍♂️`,
    `You're casually calculating mansion money, huh? 🏡`,
    `That result pays tuition and donates to charities 💸`,
    `Bro that number went to private school 😭`,
    `I had to scroll just to emotionally process that math 💀`,
    `You do math like you're funding secret government projects 🕵️‍♂️`,
    `That result could buy all my problems and sell them back with interest 💳`,
    `Your math built credit, earned rewards, and retired early 🔁`,
    `You just unlocked millionaire calculator mode 🎮💼`,
    `Your answer got its own parking space 🅿️`,
    `Even my calculator blinked when it saw that 🧠⚠️`,
    `That result belongs on a yacht eating avocado toast 🥑🛥️`,
    `You solving math like you investing in lunar real estate 🌕`,
    `That number got stock options and trust funds built-in 🧾`,
    `I wasn't ready for that kind of fiscal responsibility 😤`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};

const handleResultGreaterThanHundredThousand: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Ayo ${result}? You really flexin’ six figures on a calculator, huh? 😏`,
    `That answer lookin' like it pays rent in 3 different cities 🏙️💸`,
    `You typed ${input} and now my calculator thinks it’s a trust fund baby 💼`,
    `Your result out here wearing a tie and saying “circle back” in emails 🧑‍💻`,
    `Six-figure math on a budget UI? Love the confidence 😭`,
    `That number’s got a resume and a 9-5 💼🧾`,
    `You solving problems like you're preparing for Q4 investor calls 📊`,
    `Calculator saw ${result} and now it wants stock options 😩`,
    `That math result just bought a used Tesla 💀`,
    `You sure you’re not planning a vacation to Dubai with that answer? 🏝️`,
    `I felt that number judging me for not owning a house yet 😭`,
    `That’s the type of math that ends in “consult your accountant” 🧾📉`,
    `Your calculator now has financial goals and a vision board 📌`,
    `That result just ghosted me and bought land 💔`,
    `With numbers like that, I hope you're budgeting in peace 🧘‍♂️`,
    `That math just applied for a side hustle on LinkedIn 💼`,
    `Bro, that result walked in like “Don’t talk to me unless you earn six figs” 😤`,
    `You really typing money energy on a calculator made in CSS Grid 🤖`,
    `That result got its own podcast and eBook series 💽`,
    `Six figures? Okay entrepreneur! Where’s the business course? 👔`,
    `You solving numbers like you pay yearly rent in full 🏠💵`,
    `That answer just bought a fake blue check on X (formerly Twitter) ☑️`,
    `Not you unlocking the “I got bills and budgets” tier 💸`,
    `That number just enrolled its kids in bilingual preschool 👶🗣️`,
    `Calculator saw ${result} and asked if you want to start investing now 💹`,
    `That math just opened a Roth IRA without asking 😭`,
    `I ain’t say you rich... but your calculator charging consulting fees now 💼`,
    `That result drinks protein shakes and talks about passive income 🍹📈`,
    `Yo answer just skipped starter pack and hit mid-life crisis 😩`,
    `You doing six-figure math like it's basic multiplication. Flex harder 😤`,
    `Even commas had to take a break halfway through ${result} 😮‍💨`,
    `That math result? Definitely wears loafers and says “synergy” at work 👞`,
    `You're solving like your paycheck needs security escort 🚔`,
    `You just activated upper-middle class mode on your calculator 🔓`,
    `Not the calculator pretending it's part of the finance department 😭`,
    `That result got real estate recommendations in the suburbs 🏘️`,
    `You do math like someone that budgets by color coding Google Sheets 📊`,
    `That answer already booked its next vacation 🏝️`,
    `Your calculator got promoted to Chief Math Officer after this 🤯`,
    `Six-figure math? That’s “brunch with investors” level 🥂`,
    `Even Excel felt underqualified looking at that result 😬`,
    `You solve one equation and now your calculator has a tax attorney 🧑‍⚖️`,
    `Your answer just gave a TED Talk on responsible spending 🎤`,
    `That number files joint tax returns and itemized deductions 📑`,
    `The way ${result} looked at me, I felt financially judged 😩`,
    `Your result got a budget, savings account, and a Pinterest board 📌`,
    `You solving math like you're calculating escrow payments 🏦`,
    `That’s not math — that’s a down payment flex 💰`,
    `Six-figure vibes with a click. Okay boss 🙌`,
    `That result brought vibes and a 10-year financial plan 📆`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};

const handleResultGreaterThanAThousand: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [
    `Okay, Mr. Thousandaire. Don’t let the power go to your head 💼`,
    `You got four digits and now your calculator thinks it's better than me 😤`,
    `Wow, ${result}? Ballin' on a calculator budget 💸`,
    `Bro really said “I'm him” after crossing 1k 💀`,
    `You solving thousands like it's six figures. Calm down, champ 🧢`,
    `Not you flexing on three zeros like it's passive income 😭`,
    `That number just booked a cheap flight and called it luxury ✈️`,
    `Bro got 1,200 and started looking at Tesla stocks 💹`,
    `That result wears cologne and says “I do numbers” 😎`,
    `You typed ${input} and suddenly your calculator has an ego 🧠`,
    `That answer got you feelin’ rich until rent shows up 😬`,
    `Not the calculator poppin’ off over grocery store money 🧾`,
    `That number just bought a mattress... and not even a good one 😩`,
    `You solving four-digit math like it's top-secret intel 🕵️‍♂️`,
    `I didn’t know you were doing baller math today 😭`,
    `Your result just qualified for a low-interest personal loan 💳`,
    `That answer just screamed “starter adulting” 😆`,
    `You solving math like you’re about to buy a PS5 and still owe tax 💀`,
    `That result could fill your gas tank once. Maybe. ⛽`,
    `You really typed ${input} and expected applause? 😐`,
    `Your calculator doing thousands like it discovered Bitcoin 😤`,
    `The result just walked into the bank and got ignored 🏦`,
    `Okay, I see you Mr. Four-Digit Flex 🙄`,
    `That number looked at me and said “I’m not broke, I’m stable” 💳`,
    `This calculator out here pretending it’s a financial advisor now 📊`,
    `Bro’s math is worth exactly one used iPhone 📱`,
    `That number could buy groceries… twice 🧃`,
    `You typing math like you got options. You don’t 💀`,
    `You really flexing 1k like it comes with a mansion key 🏠`,
    `That result has just enough to be robbed, not rich 😩`,
    `The way ${result} strutted across my screen? Embarrassing 😭`,
    `That’s “I got paid but rent’s due tomorrow” math 🧾`,
    `You solving four-digit math like you balancing the UN budget 💼`,
    `That result? Straight outta "modest paycheck" energy 🔁`,
    `Bro, this ain’t wealth, it’s middle-of-the-month panic number 😂`,
    `Four digits and you’re already doing math with attitude? 😏`,
    `You typed that like your calculator now qualifies for premium 💳`,
    `That answer got no commas but got the audacity 💅`,
    `You solving thousands like the digits gonna turn into millions 😤`,
    `That result could maybe pay a semester... at YouTube University 🎓`,
    `That number just registered for a trial version of rich 😭`,
    `Your calculator turned into a “finance bro” after ${result} 💼`,
    `Math lookin’ real proud of itself for barely clearing four digits 🤨`,
    `Not you doing thousand-level math like you're in a movie montage 🎬`,
    `That number probably bought a hoodie and called it fashion 💀`,
    `You solving like your result just got verified on Instagram ☑️`,
    `Bro did four-digit math and now his calculator wants stock options 💼`,
    `You got a thousand and started doing deep breaths like a CEO 🧘‍♂️`,
    `That result got called “big money” in Monopoly only 😂`,
    `Your calculator just asked to speak to the manager after ${result} 🤖`,
    `Congrats, you hit four digits. Now go buy a sandwich 🥪`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
};

/*
 const handleResultGreaterThanATrillion: SarcasmFunction = ({ input, result }): string => {
  // const responses: string[] = [`${input} ${result}`]
  const responses: string[] = [];

  return responses[Math.floor(Math.random() * responses.length)];
};



*/

export const generateSarcasticResponse: SarcasmFunction = ({ input, result }): string => {
  // Sarcasm for easy addition
  const possibleResponses = [];
  const easyAddition = /\b([0-5])\+([0-5])\b/g;
  if (input.match(easyAddition)) {
    // ...handle easyAdditionLogic
    possibleResponses.push(handleEasyAddition({ input, result }));
  }
  const easySubtraction = /\b([0-5])-([0-5])\b/g;
  if (input.match(easySubtraction)) {
    possibleResponses.push(handleEasySubtraction({ input, result }));
  }
  //   const complicatedCalculation = /(\d+(\.\d+)?[+\-*/]){2,}\d+(\.\d+)?/;
  // const complicatedCalculation = /(\d+(\.\d+)?[+\-*/%]){2,}\d+(\.\d+)?/;
  const complicatedCalculation = /-?\d+(\.\d+)?\s*([+\-*/%]\s*-?\d+(\.\d+)?){2,}/;

  if (input.match(complicatedCalculation)) {
    if (result === "0") {
      possibleResponses.push(handleComplicatedForZero({ input, result }));
    }
    possibleResponses.push(handleComplicatedCalculations({ input, result }));
  }

  //   Handle response by result length/value
  //   Really Long result
  if (parseFloat(result) === Number.POSITIVE_INFINITY) {
    possibleResponses.push(handleReallyLongResult({ input, result }));
  }

  // Result is greater than a trillion
  if (parseFloat(result) >= 1000000000000) {
    possibleResponses.push(handleResultGreaterThanATrillion({ input, result }));
  }
  //   if result is equal or greater than a billion
  else if (parseFloat(result) >= 1000000000) {
    possibleResponses.push(handleResultGreaterThanABillion({ input, result }));
  }
  //   result greater than or equal to a million
  else if (parseFloat(result) >= 1000000) {
    possibleResponses.push(handleResultGreaterThanAMillion({ input, result }));
  }
  //   result greater than or equal to a hundred thousand
  else if (parseFloat(result) >= 100000) {
    possibleResponses.push(handleResultGreaterThanHundredThousand({ input, result }));
  }
  //   result greater than one thousand
  else if (parseFloat(result) >= 1000) {
    possibleResponses.push(handleResultGreaterThanAThousand({ input, result }));
  }

  //   Handle Fallback Responses
  if (!possibleResponses.length) {
    possibleResponses.push(fallbackResponse({ input, result }));
  }
  return possibleResponses[Math.floor(Math.random() * possibleResponses.length)];
};
